name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04 #should match whatever it runs on in production
    steps:
      #uses --> runs a specific action (a reusable piece of code)
      - uses: actions/checkout@v3 #"checksout" the source code from Git (setting v3 so doesn't break on update)
      - uses: actions/setup-node@v3
        with:
          node-version: '14.17' #again, same v as production environment
      - name: Install dependencies #technically, job names are optional
        run: npm install #starting to look familiar
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: JesTests
        run: npm test
      - name: E2E tests
        uses: cypress-io/github-action@v5 #note: this may be overkill, since it installs all the deps again?
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to production
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }} #hook stored in GitHub repository secrets
